class DevConfig:
    SECRET_KEY = '123124'
    SQLALCHEMY_DATABASE_NAME = 'development'
    SQLALCHEMY_DATABASE_USER = 'root'
    SQLALCHEMY_DATABASE_PASSWORD = 'Sbs298910?123'
    SQLALCHEMY_DATABASE_HOST = 'localhost'
    SQLALCHEMY_DATABASE_PORT = '3306'
    SQLALCHEMY_DATABASE_URI = f'mysql://{SQLALCHEMY_DATABASE_USER}:{SQLALCHEMY_DATABASE_PASSWORD}@{SQLALCHEMY_DATABASE_HOST}/{SQLALCHEMY_DATABASE_NAME}'
    
    
    
