"""empty message

Revision ID: 0fb571918c67
Revises: 34e51f44cca9
Create Date: 2024-07-25 16:51:52.681681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fb571918c67'
down_revision = '34e51f44cca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.drop_column('Updated_at')
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('lead_sales', schema=None) as batch_op:
        batch_op.drop_column('Updated_at')
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_column('Updated_at')
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_column('Updated_at')
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('Updated_at')
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Updated_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Updated_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Updated_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('lead_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Updated_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Updated_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
