"""empty message

Revision ID: 1327507bc5ae
Revises: 0fb571918c67
Create Date: 2024-07-26 22:18:09.760660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1327507bc5ae'
down_revision = '0fb571918c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('bot', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bot')
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
