"""empty message

Revision ID: 13a7f7a19c24
Revises: 7958bca727ff
Create Date: 2024-08-17 20:55:35.745842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a7f7a19c24'
down_revision = '7958bca727ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsible_assembly', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.drop_column('responsible_assembly')

    # ### end Alembic commands ###
