"""empty message

Revision ID: 352a2c83b9e8
Revises: 13a7f7a19c24
Create Date: 2024-08-18 00:49:27.286666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '352a2c83b9e8'
down_revision = '13a7f7a19c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.alter_column('assembly',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('responsible_assembly',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.alter_column('responsible_assembly',
               existing_type=sa.String(length=255),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
        batch_op.alter_column('assembly',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
