"""empty message

Revision ID: 3f0d3ca8a853
Revises: 352a2c83b9e8
Create Date: 2024-08-18 00:50:17.072765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f0d3ca8a853'
down_revision = '352a2c83b9e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_panel', sa.String(length=255), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('description_panel')

    # ### end Alembic commands ###
