"""empty message

Revision ID: 5d5f2777ffaa
Revises: af78a23c6c34
Create Date: 2024-07-25 13:55:45.215181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5f2777ffaa'
down_revision = 'af78a23c6c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklists',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('phases', sa.Integer(), nullable=True),
    sa.Column('voltage', sa.Integer(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('special_project', sa.Integer(), nullable=True),
    sa.Column('eletric_key', sa.Boolean(), nullable=True),
    sa.Column('eletric_panel', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('layout', sa.Boolean(), nullable=True),
    sa.Column('pipeline', sa.Boolean(), nullable=True),
    sa.Column('special_paint', sa.Boolean(), nullable=True),
    sa.Column('extra_filters', sa.Boolean(), nullable=True),
    sa.Column('assembly', sa.String(length=255), nullable=True),
    sa.Column('freight', sa.String(length=255), nullable=True),
    sa.Column('pallet', sa.Boolean(), nullable=True),
    sa.Column('adress', sa.String(length=255), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('other', sa.String(length=255), nullable=True),
    sa.Column('filled', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('Updated_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklists')
    # ### end Alembic commands ###
