"""empty message

Revision ID: 62f2afb60fbe
Revises: a163f346a6da
Create Date: 2024-08-13 19:44:58.728737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f2afb60fbe'
down_revision = 'a163f346a6da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_sales', schema=None) as batch_op:
        batch_op.drop_column('filled')

    # ### end Alembic commands ###
