"""empty message

Revision ID: 8a6ad7f2cffc
Revises: 1327507bc5ae
Create Date: 2024-08-09 18:26:49.063341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6ad7f2cffc'
down_revision = '1327507bc5ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('company', sa.String(255), nullable=False),
    sa.Column('phone1', sa.String(255), nullable=True),
    sa.Column('phone2', sa.String(255), nullable=True),
    sa.Column('city', sa.String(255), nullable=True),
    sa.Column('state', sa.String(255), nullable=True),
    sa.Column('created_at', sa.DateTime(255), nullable=True),
    sa.Column('updated_at', sa.DateTime(255), nullable=True),
    sa.Column('active', sa.Boolean(255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    # ### end Alembic commands ###
