"""empty message

Revision ID: a19afd7a14f8
Revises: 60ce7e938dc5
Create Date: 2024-08-19 20:38:43.199260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19afd7a14f8'
down_revision = '60ce7e938dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filter', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_sales', schema=None) as batch_op:
        batch_op.drop_column('filter')

    # ### end Alembic commands ###
