"""empty message

Revision ID: a45e3d2b54f7
Revises: ea270d38a13e
Create Date: 2024-08-20 18:37:04.176672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45e3d2b54f7'
down_revision = 'ea270d38a13e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_solds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_solds', schema=None) as batch_op:
        batch_op.drop_column('quantity')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
