"""empty message

Revision ID: efaf14ea881e
Revises: 3f0d3ca8a853
Create Date: 2024-08-18 09:36:46.428766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efaf14ea881e'
down_revision = '3f0d3ca8a853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.drop_column('adress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adress', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
